### ISSUE TITLE
More parametrization needed

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckan-docker-dcatapit#7]
There are some constants here and there that should be parametrized, e.g.
```yaml
   ports:
      - "6379:6379"
```

Keep in mind that we may want to run 2 compose in the same machine, at different versions, and they should not conflict with volumes, ports and images name.

**Comment by lpasquali** [comment]
Hello @etj 

concerning volumes, their name can be left identical in compose, because the project directory will be different and it is attached by docker-compose to the docker volume name as in example below "db" volume will be named ${PROJECT_DIR}_db so no conflict:
```
luca@vanth:~/Development/ckan-docker-dcatapit$ docker volume ls
DRIVER    VOLUME NAME
local     7a8119dba4d2403af3610939df913af28d59a39ac9de56af9e04ce47c5b4eb3f
local     ckan-docker-dcatapit_ckan-config
local     ckan-docker-dcatapit_ckan-data
local     ckan-docker-dcatapit_ckan-logs
local     ckan-docker-dcatapit_db
local     ckan-docker-dcatapit_solr-data
luca@vanth:~/Development/ckan-docker-dcatapit$
```
concerning ports, each compose will use its own docker network, so all internal ports can just be non exposed, I left $CKAN_PORT correctly configured so it can be customized as needed since there will be two ckan services.

concerning naming of images and containers I am using the env variable `COMPOSE_PROFILES` to change a string in images/containers names, while compose service names can be a costant.

Just a question @etj, is any other port to be opened to the machine hosting the two compositions or is a CKAN custom port enough?

**Comment by etj** [comment]
We may want to open the DB port or solr for debugging purposes, but it can be done in the override file, no need to provide a config for it.

**Comment by etj** [comment]
About the ports, I see the CKAN is still configured with 
```yaml
ports:
      - "0.0.0.0:${CKAN_PORT}:${CKAN_PORT}"
```
but the `ckan.ini` file is not modified accordingly.

We could just leave ckan working on port 5000, exposing that fixed port on a configurable port on the outside.

**Comment by lpasquali** [comment]
@etj sorry if I did not reply yesterday, but as you should see, I managed to configure it as it should (imo)

1) we define the finel ckan url as CKAN_SITE_URL=https://staging.ckan.adbpo.it so actually the port is never written in the application urls
2) we use  the custom port like this to customize it "outside" the ckan instance docker network for prod or staging:
```
    ports:
      - "${CKAN_PORT}:5000"
 ```
I tested this solution carefully yesterday, spawning also an identical "prod" for a little while using port 5001, it is working fine

So yes, what I did is exactly what you wrote yesterday above, PR is updated
